### ISSUE TITLE
Docs improvement 6

### ISSUE THREAD

**Issue by jscyo** [supertokens/docs#110]
- How to disable fetch interceptor that is added to the frontend (Decided not to do cause it's totally unnecessary info).
   - note that if you disable the fetch interception, then methods such as sign out or getJWTPayload may stop working.. as those use fetch. So you will also have to override those functions to use axios instead (Decided not to do cause it's totally unnecessary info).
- [x] In quick setup in various places (for quick setup, nextjs, aws lambda, netlify..), wherever we use try.supertokens.io, we should add a comment saying to replace this with the connectionURI of your core instance.
- [x] How to fetch user's email and other details (using userId or using email). This should be a new page in common customizations.
- [x] Overriding react elements examples should have an image showing the output

**Comment by rishabhpoddar** [comment]
@jscyo what's the progress on this? It's been open since 4 weeks now.
