### ISSUE TITLE
Common issues Faced, Suggestions and Questions on SupertTokens Documentation and Recipe Workflows

### ISSUE THREAD

**Issue by sowna21** [supertokens/docs#123]
Hi,

This is a **growing list** of some common issues, doc suggestions, and questions for the SupertTokens Documentation and Recipe implementation Workflows (based on my implementation).

**_Note: This list will evolve over time._**

1) 	How do I know which branch I need to switch to if I want to edit the code after I’ve cloned the code from the repo?
2) 	What are the common set up and compilation issues faced for frontend and backend code changes for the various recipes? - We could include a troubleshooting guide for the same in the relevant recipe overview pages.
3) 	What are the common issues faced for backend code changes for the various recipes?
4) 	Need to add snapshots of the steps mentioned in README.md links for all recipes.
5) 	Added frontend and backend code for Terms of service and Privacy policy but these links are not appearing in the signup page. What could be the issue?
6) 	Frequently Asked Questions page
7) 	Description of What are Recipes in the intro page.
8) 	Flow diagram of SuperTokens code for pages like Anti-CSRF implementation would be helpful.
9) Cookie Consent  page Important note "While it is not required to obtain consent for these cookies, what they do and why they are necessary should be explained to the user." – If we could provide a sample screenshot of this info it would be helpful.
10) In the using in an iframe page, could we illustrate with an example after set up in the frontend and backend like where we use this code to include the iframe of the website (using screenshots)?
11) Add more info in the introduction, screenshots and result of the implementation in the common-customizations/sessions/securing-component for all recipes.

**Comment by rishabhpoddar** [comment]
- Can you add more questions that you had whilst making the demo app (just like question 1 and question 5 in your list)?
- For things you suggest that we should do, write down a more detailed description. For example, point number 2 - where would that page be located? How would the structure of that page be?

We also have a similar list here: https://github.com/supertokens/docs/issues/5. You can move some of the points from above to this issue instead (like point number 10). But make sure those points are very, very specific and not like point 7, or 2, or 3..

Also, what's the diff between point (6) and (2 or 3)?

**Comment by rishabhpoddar** [comment]
Closing this since there is not much details in the issue about any of the steps to take
