### ISSUE TITLE
Getting Algolia search analytics

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/docs#15]
- Will help us improve docs

**Comment by rishabhpoddar** [comment]
Can do it via swizzling of search component in react, and adding analytics to that.

**Comment by jscyo** [comment]
Analytics for algolia search for the last 30 days:

**Comment by rishabhpoddar** [comment]
- How do you know how accurate this is?
- Can you get this on a continuous basis and show it on amplitude dashboard or somewhere?

**Comment by jscyo** [comment]
> How do you know how accurate this is?
These results were generated from Algolia's analytics page, I've checked the results in a sample app to see how well searches are tracked and it is accurate.

> Can you get this on a continuous basis and show it on amplitude dashboard or somewhere?
Will have to look into this.
