### ISSUE TITLE
Consider improving NestJS docs regarding session

### ISSUE THREAD

**Issue by olhapi** [supertokens/docs#185]
There are a bunch of code for getting session from request, described here (pick nestjs):
https://supertokens.io/docs/thirdpartyemailpassword/common-customizations/verify-session

But you can actually get session much easier with Session decorator (imported from @nestjs/common):

```
  @Get(':id')
  @UseGuards(AuthGuard)
  findOne(@Session() session, @Param('id') id: string) {
    console.log('session', session.getAccessTokenPayload());
    return this.candidatesService.findOne(id);
  }
```

**Comment by rishabhpoddar** [comment]
This change has been made to all recipes, and has been pushed to prod. Thanks for the suggestion!
