### ISSUE TITLE
[SQL Plugin] Develop SQL plugin

### ISSUE THREAD

**Issue by siddharthmudgal** [supertokens/docs#201]
Acceptance criteria for this ticket : 

- [ ] Queries + Unit tests or all reciepes
- [ ] Enable the entire flow from the supertokens-core module
- [ ] Update code base using the suggestions available [here](https://github.com/supertokens/supertokens-sql-plugin/pull/2])

Good to have :

- [ ] Modify the in memory plugin to be fully compatible
- [ ] Introduce liquibase
- [ ] Perform memory consumptions / load balancing tests

**Comment by rishabhpoddar** [comment]
Please recreate this issue in the sql plugin repo
