### ISSUE TITLE
Update docs to use AppInfoForm wherever possible

### ISSUE THREAD

**Issue by st-jay** [supertokens/docs#206]
## Goal
* There are many places in the docs where the `AppInfoForm` can be used to correctly display the content. We want to find all those places and add the `AppInfoForm` there.

## Where can we change it
- In `/docs/thirdpartyemailpassword/common-customizations/embed-sign-in-up-form` we can use the websiteBasePath
- In `/docs/thirdpartyemailpassword/common-customizations/reset-password/about` we can use the websiteBasePath
- In `/docs/thirdpartyemailpassword/common-customizations/reset-password/password-reset-email#send-a-custom-email` in this section, the second point can use websiteBasePath
- In `/docs/thirdpartyemailpassword/common-customizations/reset-password/embed-in-page` we can use the websiteBasePath
- In `/docs/thirdpartyemailpassword/common-customizations/email-verification/email-verification-email` we can use websiteBasePath in Send a custom email > point 3
- In `/docs/thirdpartyemailpassword/common-customizations/email-verification/embed-in-page` we can use the websiteBasePath at multiple places
- In `/docs/thirdpartyemailpassword/common-customizations/sessions/with-jwt/enabling-jwts#using-a-custom-issuer` we can use the apiDomain in the first paragraph and use the apiBasePath in the important admonition after the snipped
- In `/docs/thirdpartyemailpassword/common-customizations/changing-base-path/website-base-path` we can use the appInfoForm
- In `/docs/thirdpartyemailpassword/common-customizations/changing-base-path/api-base-path` we can use the appInfoForm
- In `/docs/thirdpartyemailpassword/hasura-integration/with-jwt#using-the-jwks-endpoint` we can use the apiDomain and apiBasePath
- On `/docs/thirdpartyemailpassword/nestjs/guide#registering-the-filter` > in the code snippet > Origin is `localhost:3000` in the `enableCors`
- On `/docs/thirdpartyemailpassword/serverless/with-netlify/auth-serverless` > The doc is written in a way where we assume that the apiBasePath is `/.netlify/functions/auth`.
- On `/docs/thirdpartyemailpassword/serverless/with-aws-lambda/frontend` > where we explain about the apiGatewayPath, we can use the appInfoForm and then explain how the endpoints with gateway paths would look ( e.g. `{apiDomain}/dev{apiBasePath}` )
- We can use the appInfoForm in `/docs/thirdpartyemailpassword/serverless/with-aws-lambda/jwt-authorizer#2-configure-your-authorizer` this section > second-last step
- The `/auth` in `/docs/thirdpartyemailpassword/serverless/with-aws-lambda/appsync-integration#2-configure-the-api-gateway-with-the-authorizer` > first paragraph can be replaced with the apiBasePath
- In `/docs/thirdpartyemailpassword/testing/testing-with-postman` we use `/auth` and `localhost:3001` multiple times, these can be replaced with `apiBasePath` and `apiDomain` respectively.
- `/docs/thirdpartyemailpassword/migration/from-auth0/session-migration#frontend-changes` > `apiDomain` can be used in the code snippet
- Common Customisations -> Changing Base Path: The content will need to change slightly because we now use the form value for base paths and dont default to "/auth" everywhere in the docs.

**Comment by rishabhpoddar** [comment]
I think this is already done. Closing this. Feel free to repoen in case it's not done
