### ISSUE TITLE
Documentation changes for supertokens-web-js

### ISSUE THREAD

**Issue by nkshah2** [supertokens/docs#208]
# Plan

The documentation for frontend SDKs should be split with the fundamental question of whether or not the user intends to use our pre-built UI. If yes then we show docs for React SDK only, if no then we show docs for all SDKs (here the react sdk docs will need to change to assume they dont use the pre-built UI)

# Implementation options

## OPTION 1

The general layout for the documentation remains the same, at the top of every page that requires choosing between pre-built UI and custom UI we add the Question component for whether or not the user wants to use custom ui (The question component will need to change to save the selected option in localstorage)

### Pros

- The structure of docs more or less remains the same, the only thing that changes is the docs pages themselves
- Adding localstorage capacity to Question will make this friction a one time thing

### Cons

- Can add confusion to the documentation
- Each page will open to just the Question component initially which can feel weird (and might affect SEO)

## OPTION 2

We change the layout of the docs in the side bar where we group pages based on whether they use pre-built UI or not.

### Pros

- Once the user lands on a page there is no friction or confusion

### Cons

- Significant refactor of docs structure
- Changes in docs now require changes in twice the files (one for pre-built other for custom)
- Will make finding the right page on the docs more challenging

## Option 3 (My choice)

Each page that requires separate docs for pre-built UI and custom UI has top level tabs on the page (defaulting to pre-built if nothing is present in localstorage). 

### Pros

- Content for existing use cases remains more or less the same, changes will mainly be refactors of the existing docs
- Docs structure does not need to change

### Cons

- Additional tab on all relevant pages
- Additional choice on the start of the page (possible friction point)

**Comment by rishabhpoddar** [comment]
I prefer an option where:
- You show all the frameworks (react, vanilla js, RN)
- Under reactJS, we show a question (which is saved in localstorage) if they want to use the pre built UI or not
- Based on that, we show content

We also need to add extra pages for custom UI which talk about how to do sign in etc etc..
