### ISSUE TITLE
Error in error handler fastify docs :thirdparty

### ISSUE THREAD

**Issue by sreehari2003** [supertokens/docs#387]
![image](https://user-images.githubusercontent.com/66205494/178792924-15e6c29f-9323-45ac-8b6c-7319e8634916.png)
## here the comment ```//your  apiroutes``` should  be before calling the error handler function right ?  if this is a bug pls assign this to me btw i foud this bug on https://supertokens.com/docs/thirdparty/quick-setup/backend

**Comment by rishabhpoddar** [comment]
Ah right yea. You are correct! Thanks for pointing this out. I have assigned the issue to you

**Comment by rishabhpoddar** [comment]
hey! I'm not sure if the dev env will work on Windows. We have made it for Mac or Linux only. Try using with wsl2: https://docs.microsoft.com/en-us/windows/wsl/about

**Comment by rishabhpoddar** [comment]
hey @sreehari2003 on reconsideration, I think the error handler being before all the api routes and the plugin registration is actually correct. Do you have an example where it breaks if you add it before?
