### ISSUE TITLE
Promise resolve vs reject function signature in reference docs

### ISSUE THREAD

**Issue by makeitcount** [supertokens/docs#403]
Currently, the reference docs write `Promise<ResolveFnSignature1|ResolveFnSignature2>` (e.g. `Promise<{ fetchResponse: Response; status: "OK"; user: UserType } | { fetchResponse: Response;  status: "FIELD_ERROR" }>`), which led to misunderstanding. 

To avoid this confusion, we can follow the convention and write `Promise<ResolveFnSignature|RejectFnSignature>`. 

But what if resolve fn has two types of signature? Mark the properties as optional e.g. `Promise<{ fetchResponse: Response; status: "OK" | "FIELD_ERROR"; formFields?: { error: string; id: string }[]; user?: UserType } | { this one for reject fn signature }>`

**Comment by rishabhpoddar** [comment]
> Promise<ResolveFnSignature|RejectFnSignature>.

The type in the `<>` will always be the type of something that is resolved. Therefore it makes little sense to add the type of a rejection in there.

The reason we have `FIELD_ERROR` as a resolve and not as reject is cause we want to encourage the developer to handle this type of response by changing the UI specifically for this error type (As opposed to showing a generic something went wrong message).

No action is required here, so closing this issue.
