### ISSUE TITLE
Passwordless setup for js missing passwordless.js import

### ISSUE THREAD

**Issue by makeitcount** [supertokens/docs#423]
1. Go to https://supertokens.com/docs/passwordless/quick-setup/frontend
2. Select plain javacript
3. The imports should also have `passwordless.js` import otherwise the recipe won't work
```
<script src="https://cdn.jsdelivr.net/gh/supertokens/supertokens-web-js/bundle/passwordless.js"></script>
```

**Comment by rishabhpoddar** [comment]
We are working on these docs.
