### ISSUE TITLE
Passwordless recipe js frontend setup missing init fn

### ISSUE THREAD

**Issue by makeitcount** [supertokens/docs#424]
1. Go to page - https://supertokens.com/docs/passwordless/quick-setup/frontend#2-call-the-init-function
2. Choose plain javascript

The Passwordless init fn is missing. This will result in frontend code not working. 

ToDO: Add this code to recipe list

```
supertokensPasswordless.init({
    contactMethod: "EMAIL_OR_PHONE"
}),
```

**Comment by rishabhpoddar** [comment]
We are working on adding more info on how to use the web-js SDK for all recipes.
