### ISSUE TITLE
URL is broken

### ISSUE THREAD

**Issue by Taikono-Himazin** [supertokens/docs#470]
https://github.com/supertokens/docs/blob/master/v2/thirdpartyemailpassword/common-customizations/styling/themes.mdx

If you click on the "here" part of the text below, a 404 will be displayed.

> Combining the techniques described in the previous two sections we have created three themes which can be found here.

**Comment by rishabhpoddar** [comment]
Hey! This is a deprecated page in the docs (not available for view on the sidebar). That being said, I will make it redirect to the right page in the docs. Thanks
