### ISSUE TITLE
Design - Multi tab ui for documentation

### ISSUE THREAD

**Issue by mufassirkazi** [supertokens/docs#62]

**Comment by mufassirkazi** [comment]
Here are the various options: https://zpl.io/VKB4BPJ

I've marked the ones that I like with a green tick. But feel free to choose whichever one you like @rishabhpoddar

**Comment by rishabhpoddar** [comment]
Related to https://github.com/supertokens/docs/issues/52

**Comment by mufassirkazi** [comment]
https://zpl.io/V4GAlYy

@rishabhpoddar

**Comment by mufassirkazi** [comment]
https://zpl.io/2yoBw89

**Comment by mufassirkazi** [comment]
I don't know if this is already being done, but putting it out in the wild. 

Whenever a user selects a particular tech stack in the tab options, all the code snippets for the whole documentation should switch to that tech stack.

**Comment by rishabhpoddar** [comment]
Yes! This is a good idea. Docusaurus v2 has support for this. So will do it.
