### ISSUE TITLE
docker-compose healthcheck errors

### ISSUE THREAD

**Issue by trivialkettle** [supertokens/docs#677]
Hi,
I hope this is the right repository for this issue.

I use the docker-compose.yml file to run supertokens with postgresql
https://supertokens.com/docs/emailpassword/pre-built-ui/setup/core/with-docker#docker-compose-file

In the docker logs you can see the following error during health check:
```
fatal role "root" does not exist
```

I fixed this in my docker-compose by setting the correct user:
```
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'supertoken_user', '-d', 'supertokens']
```

I am not sure if there is a better way to handle this, but I don't get the error anymore.

**Comment by trivialkettle** [comment]
I found https://github.com/supertokens/docs/pull/633 that removed the user, but there is no explanation why.

**Comment by rishabhpoddar** [comment]
Thanks. We have updated our docs!
