### ISSUE TITLE
Golang emailpassword recipe change email RequestBody struct

### ISSUE THREAD

**Issue by trivialkettle** [supertokens/docs#705]
Hi

at https://supertokens.com/docs/emailpassword/common-customizations/change-email-post-login

The struct
```
type RequestBody struct {
    email string
}
```

Should have uppercase member
```
type RequestBody struct {
    Email string
}
```
to make the json decoding working

**Comment by rishabhpoddar** [comment]
Thanks for this! We will fix this in the next docs update (will be out in a few days).

**Comment by Abhicodeitout** [comment]
https://github.com/supertokens/docs/pull/708

**Comment by rishabhpoddar** [comment]
Hey @Abhicodeitout sorry, but we have already made this change in our next major release. So i will have to close your PR.

**Comment by Abhicodeitout** [comment]
Ohk

**Comment by rishabhpoddar** [comment]
This has now been fixed in the docs.
