### ISSUE TITLE
v2 Styling improvements

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/docs#71]
- [ ] Style of resubmit info? i too prominent
- [ ] once the form is submitted, we should also show the values that they filled in along with the resubmit button (in a concise way)
Remaining TODOs:
- [ ] The documentation looks cluttery on first glance even though it isnt
   - Font sizes should be smaller
   - Sidebar should have more spacing and clear divisions
   - Right bar can be made smaller
   - Left image: https://supertokens.io/docs/thirdpartyemailpassword/quick-setup/backend#2-initialise-supertokens
   - Right Image: https://firebase.google.com/docs/crashlytics/get-started?platform=android
- [ ] Checkbox thing for get started page. And then depending on which options they select, we filter the options. We can keep options we don’t have, and then when they select those, we tell them we don’t have, but we get to know which option they selected. Also, people getting lost in documentation because of being in the wrong recipe can also be solved, by telling them, that these are docs for this recipe, to view docs for the recipe you want, please visit our getting started page. If someone selects a recipe, we save their value in local storage, then when they go to google search something and land on a different url for a different recipe, , then we tell them in a big red box, this is docs for this recipe, based on your selected preferred recipe, we think you should visit  these docs.
- [ ] Your app configuration details: It resolves to and error state. To be added. Add it directly in the input field only. So stretch the height of the input field. So, if they type, example.com. Then give a green state: It resolves to http://www.example.com
- [ ] Hey Mufassir, working on the documentation since last few days, one of the most annoying part is the color combination. It just hurt to look at. I guess this is the reason most of the sdk documentation is with white background. One good documentation with dark theme is Stripe which also reduces the intensity of white in the fonts and I think it also has lesser font weight. Give different color options, and then rishabh will create a PR for each option and people can navigate and test it out as to which combo they liked best?
- [ ] Change the ui of the links in the important/ caution and different messages boxes. They don't seem apparent enough
- [ ] Should the placement be different or can we make the important boxes (caution, danger, important, info) more important somehow?
- [ ] FDI and CDI diagrams - - in the architecture diagram that has FDI and CDI labelled in it, the focus should be on FDI and CDI. You don't need sign in and sign out flow and you don't need self hosted and managed service - just frontend, backend and core.
- [ ] Strong popup heirarcy, for pages where content is too long. So main points become sticky as you scroll to give you indication under which section you are in. For that you'll have to surrond each point under a div container so that you seperate out the points
- [ ] Redesign subtabs
- [ ] CSS style changes
- [ ] code highlight colour
- [ ] Showing path of current docs on top of the docs page
- [ ] Getting started recipe tab items - make uniform

- [ ] Change color of caution box
- [ ] I think column width is far too large. Readability and text size of current is much better
- [ ] Navigation is confusing at times. There should be something at the top of the page that indicates how deep down you are in the documentation. If I give someone a direct link to one of the deeper nested documentation pages, the new visitor will be completely confused as to where he has landed. I suggest we remove “See all recipes” thing that we have in the header (beside the logo) and instead on every page, we have links to all the main navigation fields. So for eg, if I’m inside sign out, common customisations of thirdpartyemailpassword recipe, the top of the page should indicate: Home / Recipes / Email password + Social Login / Common customisations 
   - If I click on home, it should take me to the introduction page of docs. 
   - Recipes takes me to where all docs are listed
   - Email password + Social Login takes me to the “About this recipe” page
   - Common customisation takes me to the first link inside the dropdown
At all times I should have an idea of where exactly I am.

- [ ] Images should have ability to zoom in / expand? I cannot decipher what is being shown in the postman screen (https://test.supertokens.io/docs/emailpassword/testing/testing-with-postman)

**Comment by mufassirkazi** [comment]
### Explained what the red element is on the front end
**Self Hosted**

![selfhosted_flow.png](https://images.zenhubusercontent.com/60e449b3d731ab0e662b3376/1a4bd485-ad69-4480-8fde-0680daba225d)

**Managed Service**
![managedservice_flow.png](https://images.zenhubusercontent.com/60e449b3d731ab0e662b3376/7f613aa1-5b24-48fa-9d43-2bacd9c62f41)

### Validate input and verify session inside the yellow block

**Self Hosted**
![selfhosted_flow – 1.png](https://images.zenhubusercontent.com/60e449b3d731ab0e662b3376/c87a93cd-fc3e-48d1-86dc-160f4154b8be)

**Managed Service**

![managedservice_flow – 1.png](https://images.zenhubusercontent.com/60e449b3d731ab0e662b3376/74326be8-cfee-49a5-ad10-2f355126af80)


### Removed the API frontend driver interface and core driver interface

**Self hosted**
![selfhosted_flow – 2.png](https://images.zenhubusercontent.com/60e449b3d731ab0e662b337 6/54fcd327-2bc7-4373-a858-4556aadf5fe0)

**Managed Service**
![managedservice_flow – 2.png](https://images.zenhubusercontent.com/60e449b3d731ab0e662b3376/b12d18f5-310c-4b7e-9f61-45959a9e562b)

Please pick whichever version you like best. 


> Can we colour code the support tech stacks section in the intro
Some iterations: https://zpl.io/bzxj794

**Comment by rishabhpoddar** [comment]
- I don't like the validation inside the yellow box. I think what we have now is better.
- I prefer to keep the CDI and FDI in the diagram.
- I don't think writing SuperTokens SDK on top of the red thing makes any diff cause that section already has Frontend SDK written.
- I liked this one the most: 
<img width="358" alt="Screenshot 2021-07-28 at 14 08 31" src="https://user-images.githubusercontent.com/2976287/127291917-65527940-a38a-4490-9041-6b92e279bea5.png">

**Comment by mufassirkazi** [comment]
> there is this red element on the frontend that isnt explained when everything else is

> I don't think writing SuperTokens SDK on top of the red thing makes any diff cause that section already has Frontend SDK written.


The red element is SuperTokens SDK which wasn't explained - so I did it. Or did Advait mean something else?

> I don't like the validation inside the yellow box. I think what we have now is better.
> I prefer to keep the CDI and FDI in the diagram.

Agree with both.

**Comment by mufassirkazi** [comment]
>  I think column width is far too large. Readability and text size of current is much better

```
Requires following changes: 

<header> - margin-bottom: 48px

<h1> 
Font-size: 3rem
Font-weight: bold
Margin-bottom: 25px
</h1>

</header>


<h2>
Font-size: 2rem
Margin-top: 40px
Margin-bottom: 20px
Font-weight: bold

</h2>


<h3>
Font-size: 1.5rem
Margin-top: 30px
Margin-bottom: 20px
</h3>

<h4>
Font-size: 1.25rem
</h4>

<h5>
Font-size: 1rem
</h5>

<h6>
Font-size: 0.875rem
</h6>



<ul>
Margin-bottom: 20px
</ul>


<p>
Margin-bottom: 20px
</p>

Font-size-base: 15px
Line-height-base: 27px

The menu list of the left should have a total width of 235px
Font-weight: 500
Font-size: 14px
Margin-top 20px

Each list item inside the menu should have a top and bottom padding of 8px. 

Code part should have font size 13px
The tab selection for code snippets should be redone to reflect this design: https://zpl.io/VqQJ75m


Screen size: between >997 to <=1060
The div class="docItemContainer_1EXp" width is 440 and should have padding-right and left of 32 px


Screen size: between >1060 to <=1320

The div class="docItemContainer_1EXp" width is 510px and should have padding-right and left of 32 px
The whole div with class=“row” should be centre aligned along the screen space


Screen size: between >1320 to <=1440

The div class="docItemContainer_1EXp" width is 741px and should have padding-right and left of 32 px
The whole div with class=“row” should be centre aligned along the screen space


Screen size: between >1440 to <=4000
The div class="docItemContainer_1EXp" width is 759px and should have padding-right and left of 32 px
The whole div with class=“row” should be centre aligned along the screen space

```


**Main architecture page**

**_Self hosted_**
![selfhosted_flow – 4.png](https://images.zenhubusercontent.com/60e449b3d731ab0e662b3376/8f1ec904-7705-47c2-9768-6f4da10ece72)

**_Managed service_**
![managedservice_flow – 4.png](https://images.zenhubusercontent.com/60e449b3d731ab0e662b3376/7c61e915-ff40-417e-a63c-99b0d9656819)

**Architecture diagram v2 - for api reference page** 

**_Self hosted_**

![selfhosted_flow – 5.png](https://images.zenhubusercontent.com/60e449b3d731ab0e662b3376/13d6506d-1f40-4cb8-ba97-8e7a743acd1b)

**_Managed service_**
![managedservice_flow – 5.png](https://images.zenhubusercontent.com/60e449b3d731ab0e662b3376/c9874256-0bd6-40b7-a274-59e35bf2d922)


>  Can we colour code the support tech stacks section in the intro? Green for Nodejs, orange for python / Golang and red for php / java. Same scheme for the frontend

Design: https://zpl.io/Vx9ZWEw

>  Maybe an issue isolated to my screen but its a little hard to make out the highlights in code snippets.

Please change highlight colour to #2b2b2b

> Navigation is confusing at times...

Design: https://zpl.io/2yoBw89


> Images should have ability to zoom in / expand?

Can we do something like having a magnifying glass icon to expand images? Pretty common nowadays to expand an image

>  On second thoughts, all the info states (caution, important, danger, etc) are too bold colours which hit the eye. Maybe we should do some lighter versions of the same color?

```
Keep the borders of all the  states intact. Just changes their background colours
Change the yellowish/orangish to (Caution one): #ffe6a2
Change the greenish one to: #8fff8f
Change the bluish one to: #89e2ff
```

>  Recipes list can be a simple box grid with all boxes having the same height and width, I think uniform UI usually adds to readability

This change should be done along with the changes of fixing column width to increase readability. 

Design 1: zpl.io/bAK13Yp (this is current version design with new font sizes to match across documentation)
Design 2: https://zpl.io/aNYQ3kv (this is a version that makes all the boxes have the same height and width)

>  In the Recipe > Quick setup > Core > Managed Service Page “Click on the blue "Connect" button, and you will see:” should not mention the colour in case we change the design and don’t realise we need to update the docs

Instead of indicating the colour of the button, just highlight the part of interest in the screen shot and while referring to it in the documentation use "Please click on the highlighted button in the above picture / screenshot" or something similar

>  Some screenshots can be GIFs, for example In the Recipe > Quick setup > Core > Managed Service Pages the part about clicking on the connect button and seeing a dialog would be easier to understand with a GIF

If the process in question involves more than 1/2 steps, please have it converted to GIFs.

>  For ‘about appInfo’ page, I would additionally provide a complete example of valid appInfo object.
To be done by engineering team

**Comment by rishabhpoddar** [comment]
# Comments in progress..
@mufassirkazi 
- the css styling needs to be redone.
- in the architecture diagram that has FDI and CDI labelled in it, the focus should be on FDI and CDI. You don't need sign in and sign out flow and you don't need self hosted and managed service - just frontend, backend and core.
- Code snippet colour doesn't look good. So as discussed, keeping it to normal
- The path thing on top of page is not easy to do, so make it as a separate issue..
- The change regarding about appInfo page, each section already has example values and in quick setup (frontend and backend), we already have an example, minimal, appInfo object. I will add a type definition of the appInfo object on the file.

**Comment by rishabhpoddar** [comment]
Please see https://github.com/supertokens/docs/pull/92 for many of the changes.. and there is also a TODO list which has pending changes.

**Comment by rishabhpoddar** [comment]
@mufassirkazi please see the PR link above and fix the issues in design as per my previous comment.

**Comment by rishabhpoddar** [comment]
Remaining TODOs:
- [ ] FDI and CDI diagrams
- [ ] CSS style changes
- [ ] code highlight colour
- [ ] Showing path of current docs on top of the docs page
- [ ] Getting started recipe tab items - make uniform

**Comment by mufassirkazi** [comment]
Change caution state color to :#ffdd80

**Comment by rishabhpoddar** [comment]
@mufassirkazi I feel like the colour of caution is still not good. Please have many options and put it as a vote.

**Comment by rishabhpoddar** [comment]
Clsoing due to inactivity.
