### ISSUE TITLE
Get Algolia search to work again in docs

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/docs#72]
Right now, if you open the docs, search for "gett" instead of showing the getting started page, it throws an error (in the console),

**Comment by rishabhpoddar** [comment]
@jscyo please test out the search - it seems that they have finished crawling the new docs.

**Comment by jscyo** [comment]
Just finished testing the changes the latest crawl did. It seems that there were pages missing when crawling.  For example on https://supertokens.io/docs/emailpassword/introduction we are getting results for multi-tennancy and User pagination sections but no results for the Sign out and Redirect to auth Screen sections. This sort of inconsistent crawling is happening on most pages. When testing it out locally the fix seemed to be just increasing the `js_wait` time. Previously though the algolia maintainer said that if you increase the `js_wait` too much it can cause their crawler to fail. I have relayed this issue with the algolia maintainer through discord

**Comment by jscyo** [comment]
> Right now, if you open the docs, search for "gett" instead of showing the getting started page, it throws an error (in the console),

The issue seems to be resolved though

**Comment by rishabhpoddar** [comment]
@jscyo we may not need the js wait time now cause we have proper server side rendering. All content on the page is shown even if JS is disabled. 

So please rethink this and do it properly.

**Comment by rishabhpoddar** [comment]
Seems to work fine now.
