### ISSUE TITLE
Documentation changes for branch 7.0 supertokens-node

### ISSUE THREAD

**Issue by bhumilsarvaiya** [supertokens/docs#78]
Changes related
- [x] req-res wrapper changes (related to https://github.com/supertokens/supertokens-node/pull/146)

**Comment by rishabhpoddar** [comment]
- @bhumilsarvaiya where is the PR for this?
- What changes would be required for the OAuth scope in docs?

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya i have merged the associated PR into another branch that has other changes related to 7.0 version of the node SDK: https://github.com/supertokens/docs/pull/95

So please see that and see https://github.com/supertokens/docs/pull/95#issuecomment-912918387 comment.
